#!/usr/bin/env python3
"""
This will get the input and query the current price.
input: stdin
output: stdout

Example input:
{
  "source": {},
  "version": {
    "price": "2000"
  }
}

Example output:
'{"version":{"price":"2010"}}'
"""

from __future__ import print_function
import sys
import json
import requests

save_stdin = json.loads(sys.stdin.read())
bitcoin_api_url = 'https://api.coinmarketcap.com/v1/ticker/bitcoin/'

response = requests.get(bitcoin_api_url)
response = response.json() # use buildin json decoder
price = str(float(response[0]['price_usd']))

# write prize to file
with open("price.txt", "w") as text_file:
    print(price, file=text_file)

version = {'price': price}
callback = json.dumps(version)
print("{\"version\":" + callback + "}")
